name = "{{ service.name }}"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"