use crate::types::{Result, RuneWeaveError};
use git2::{Cred, PushOptions, RemoteCallbacks, Repository, Signature};
use std::path::Path;
use std::process::Command;

pub async fn push_to_repo(local_path: &Path, repo_url: &str, public: bool) -> Result<()> {
    if !repo_url.starts_with("github:") {
        return Err(RuneWeaveError::GitError(git2::Error::from_str(
            "Only GitHub repositories are supported (use github:owner/repo format)",
        )));
    }

    let github_path = repo_url.trim_start_matches("github:");
    let parts: Vec<&str> = github_path.split('/').collect();
    if parts.len() != 2 {
        return Err(RuneWeaveError::GitError(git2::Error::from_str(
            "Invalid GitHub repository format. Use github:owner/repo",
        )));
    }

    let (owner, repo_name) = (parts[0], parts[1]);

    let output = Command::new("gh")
        .args(&["auth", "status"])
        .output()
        .map_err(|e| {
            RuneWeaveError::GitError(git2::Error::from_str(&format!(
                "GitHub CLI not found or not authenticated: {}",
                e
            )))
        })?;

    if !output.status.success() {
        return Err(RuneWeaveError::GitError(git2::Error::from_str(
            "GitHub CLI not authenticated. Run 'gh auth login' first",
        )));
    }

    let visibility = if public { "--public" } else { "--private" };
    let create_output = Command::new("gh")
        .args(&[
            "repo",
            "create",
            &format!("{}/{}", owner, repo_name),
            visibility,
            "--clone=false",
        ])
        .output()
        .map_err(|e| {
            RuneWeaveError::GitError(git2::Error::from_str(&format!(
                "Failed to create GitHub repository: {}",
                e
            )))
        })?;

    if !create_output.status.success() {
        let stderr = String::from_utf8_lossy(&create_output.stderr);
        if !stderr.contains("already exists") {
            return Err(RuneWeaveError::GitError(git2::Error::from_str(&format!(
                "Failed to create repository: {}",
                stderr
            ))));
        }
    }

    let repo = match Repository::init(local_path) {
        Ok(repo) => repo,
        Err(_) => Repository::open(local_path)?,
    };

    let mut index = repo.index()?;
    index.add_all(["*"].iter(), git2::IndexAddOption::DEFAULT, None)?;
    index.write()?;

    let tree_id = index.write_tree()?;
    let tree = repo.find_tree(tree_id)?;

    let sig = Signature::now("RuneWeave", "runeweave@example.com")?;
    
    let parent_commit = match repo.head() {
        Ok(head) => Some(head.peel_to_commit()?),
        Err(_) => None,
    };

    let parent_commits = parent_commit
        .as_ref()
        .map(|c| vec![c])
        .unwrap_or_default();

    let parent_refs: Vec<&git2::Commit> = parent_commits.iter().copied().collect();

    repo.commit(
        Some("HEAD"),
        &sig,
        &sig,
        "Initial scaffold generated by RuneWeave",
        &tree,
        &parent_refs,
    )?;

    let remote_url = format!("https://github.com/{}/{}.git", owner, repo_name);
    let mut remote = match repo.find_remote("origin") {
        Ok(remote) => remote,
        Err(_) => repo.remote("origin", &remote_url)?,
    };

    let mut callbacks = RemoteCallbacks::new();
    callbacks.credentials(|_url, username_from_url, _allowed_types| {
        Cred::ssh_key_from_agent(username_from_url.unwrap_or("git"))
    });

    let mut push_options = PushOptions::new();
    push_options.remote_callbacks(callbacks);

    remote.push(&["refs/heads/main"], Some(&mut push_options))?;

    println!("✓ Repository created at: https://github.com/{}/{}", owner, repo_name);

    Ok(())
}