use crate::types::{Plan, Result, RuneWeaveError, ServiceType};
use rand::SeedableRng;
use rand_chacha::ChaCha8Rng;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use tera::{Context, Tera};

pub fn generate_scaffold(plan: &Plan, seed: u64, output_dir: &Path) -> Result<Vec<String>> {
    let mut rng = ChaCha8Rng::seed_from_u64(seed);
    let mut files_generated = Vec::new();

    fs::create_dir_all(output_dir)?;

    let mut tera = Tera::default();
    load_templates(&mut tera)?;

    let mut context = Context::new();
    context.insert("project", &plan.project);
    context.insert("services", &plan.services);
    context.insert("tools", &plan.tools);
    context.insert("infrastructure", &plan.infrastructure);

    write_workspace_cargo_toml(output_dir, &plan, &mut files_generated)?;
    write_rust_toolchain(output_dir, &plan, &mut files_generated)?;
    write_gitignore(output_dir, &mut files_generated)?;

    for service in &plan.services {
        generate_service(output_dir, service, &plan, &mut tera, &mut context, &mut files_generated)?;
    }

    if let Some(tools) = &plan.tools {
        for tool in tools {
            generate_tool(output_dir, tool, &plan, &mut tera, &mut context, &mut files_generated)?;
        }
    }

    write_github_workflows(output_dir, &plan, &mut tera, &mut context, &mut files_generated)?;

    Ok(files_generated)
}

fn write_workspace_cargo_toml(
    output_dir: &Path,
    plan: &Plan,
    files: &mut Vec<String>,
) -> Result<()> {
    let mut members = vec![];

    for service in &plan.services {
        members.push(format!("services/{}", service.name));
    }

    if let Some(tools) = &plan.tools {
        for tool in tools {
            members.push(format!("tools/{}", tool.name));
        }
    }

    let content = format!(
        r#"[workspace]
members = {}
resolver = "2"

[workspace.package]
version = "{}"
edition = "2021"
rust-version = "{}"
authors = ["Generated by RuneWeave"]
repository = "{}"
license = "{}"

[workspace.dependencies]
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
anyhow = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[profile.release-wasm]
inherits = "release"
opt-level = "z"
"#,
        serde_json::to_string(&members)?,
        plan.project.version,
        plan.project.rust_version.as_deref().unwrap_or("1.80"),
        plan.project.repository.as_deref().unwrap_or(""),
        plan.project.license.as_deref().unwrap_or("MIT OR Apache-2.0"),
    );

    let path = output_dir.join("Cargo.toml");
    fs::write(&path, content)?;
    files.push("Cargo.toml".to_string());
    
    Ok(())
}

fn write_rust_toolchain(
    output_dir: &Path,
    plan: &Plan,
    files: &mut Vec<String>,
) -> Result<()> {
    let rust_version = plan.project.rust_version.as_deref().unwrap_or("stable");
    
    let content = format!(
        r#"[toolchain]
channel = "{}"
components = ["rustfmt", "clippy"]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-musl"]
profile = "minimal"
"#,
        rust_version
    );

    let path = output_dir.join("rust-toolchain.toml");
    fs::write(&path, content)?;
    files.push("rust-toolchain.toml".to_string());
    
    Ok(())
}

fn write_gitignore(output_dir: &Path, files: &mut Vec<String>) -> Result<()> {
    let content = r#"/target
**/*.rs.bk
Cargo.lock
*.pdb
.DS_Store
.env
.env.local
*.log
node_modules/
dist/
.wrangler/
"#;

    let path = output_dir.join(".gitignore");
    fs::write(&path, content)?;
    files.push(".gitignore".to_string());
    
    Ok(())
}

fn generate_service(
    output_dir: &Path,
    service: &crate::types::ServiceConfig,
    plan: &Plan,
    tera: &mut Tera,
    context: &mut Context,
    files: &mut Vec<String>,
) -> Result<()> {
    let service_dir = output_dir.join("services").join(&service.name);
    fs::create_dir_all(&service_dir)?;

    context.insert("service", service);

    match service.service_type {
        ServiceType::Api => generate_api_service(&service_dir, service, plan, tera, context, files),
        ServiceType::ApiEdge => generate_edge_service(&service_dir, service, plan, tera, context, files),
        ServiceType::Worker => generate_worker_service(&service_dir, service, plan, tera, context, files),
        ServiceType::Library => generate_library(&service_dir, service, plan, tera, context, files),
    }
}

fn generate_api_service(
    service_dir: &Path,
    service: &crate::types::ServiceConfig,
    plan: &Plan,
    tera: &mut Tera,
    context: &mut Context,
    files: &mut Vec<String>,
) -> Result<()> {
    let cargo_content = format!(
        r#"[package]
name = "{}"
version = "{}"
edition = "2021"
rust-version = "{}"

[dependencies]
actix-web = "4"
actix-rt = "2"
tokio = {{ workspace = true }}
serde = {{ workspace = true }}
serde_json = {{ workspace = true }}
anyhow = {{ workspace = true }}
tracing = {{ workspace = true }}
tracing-subscriber = {{ workspace = true }}
env_logger = "0.11"
"#,
        service.name,
        plan.project.version,
        plan.project.rust_version.as_deref().unwrap_or("1.80"),
    );

    fs::write(service_dir.join("Cargo.toml"), cargo_content)?;
    files.push(format!("services/{}/Cargo.toml", service.name));

    let main_content = r#"use actix_web::{web, App, HttpResponse, HttpServer, middleware};
use serde::{Deserialize, Serialize};
use tracing::info;

#[derive(Serialize, Deserialize)]
struct HealthResponse {
    status: String,
    service: String,
}

async fn health() -> HttpResponse {
    HttpResponse::Ok().json(HealthResponse {
        status: "healthy".to_string(),
        service: env!("CARGO_PKG_NAME").to_string(),
    })
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    tracing_subscriber::fmt::init();
    
    info!("Starting {} server", env!("CARGO_PKG_NAME"));

    HttpServer::new(|| {
        App::new()
            .wrap(middleware::Logger::default())
            .route("/health", web::get().to(health))
    })
    .bind("0.0.0.0:8080")?
    .run()
    .await
}
"#;

    let src_dir = service_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    fs::write(src_dir.join("main.rs"), main_content)?;
    files.push(format!("services/{}/src/main.rs", service.name));

    Ok(())
}

fn generate_edge_service(
    service_dir: &Path,
    service: &crate::types::ServiceConfig,
    plan: &Plan,
    tera: &mut Tera,
    context: &mut Context,
    files: &mut Vec<String>,
) -> Result<()> {
    let cargo_content = format!(
        r#"[package]
name = "{}"
version = "{}"
edition = "2021"
rust-version = "{}"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.0.18"
serde = {{ workspace = true }}
serde_json = {{ workspace = true }}
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
"#,
        service.name,
        plan.project.version,
        plan.project.rust_version.as_deref().unwrap_or("1.80"),
    );

    fs::write(service_dir.join("Cargo.toml"), cargo_content)?;
    files.push(format!("services/{}/Cargo.toml", service.name));

    let lib_content = r#"use worker::*;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
struct HealthResponse {
    status: String,
    service: String,
    region: Option<String>,
}

#[event(fetch)]
pub async fn main(req: Request, env: Env, _ctx: Context) -> Result<Response> {
    console_error_panic_hook::set_once();

    Router::new()
        .get("/health", |_, ctx| async move {
            let region = ctx.env.var("CF_REGION").ok().map(|v| v.to_string());
            
            Response::from_json(&HealthResponse {
                status: "healthy".to_string(),
                service: env!("CARGO_PKG_NAME").to_string(),
                region,
            })
        })
        .run(req, env)
        .await
}
"#;

    let src_dir = service_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    fs::write(src_dir.join("lib.rs"), lib_content)?;
    files.push(format!("services/{}/src/lib.rs", service.name));

    let wrangler_content = format!(
        r#"name = "{}"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"

[build]
command = "cargo install -q worker-build && worker-build --release"

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"
"#,
        service.name
    );

    fs::write(service_dir.join("wrangler.toml"), wrangler_content)?;
    files.push(format!("services/{}/wrangler.toml", service.name));

    Ok(())
}

fn generate_worker_service(
    service_dir: &Path,
    service: &crate::types::ServiceConfig,
    plan: &Plan,
    tera: &mut Tera,
    context: &mut Context,
    files: &mut Vec<String>,
) -> Result<()> {
    generate_library(service_dir, service, plan, tera, context, files)
}

fn generate_library(
    service_dir: &Path,
    service: &crate::types::ServiceConfig,
    plan: &Plan,
    tera: &mut Tera,
    context: &mut Context,
    files: &mut Vec<String>,
) -> Result<()> {
    let cargo_content = format!(
        r#"[package]
name = "{}"
version = "{}"
edition = "2021"
rust-version = "{}"

[dependencies]
serde = {{ workspace = true }}
serde_json = {{ workspace = true }}
anyhow = {{ workspace = true }}
thiserror = {{ workspace = true }}
"#,
        service.name,
        plan.project.version,
        plan.project.rust_version.as_deref().unwrap_or("1.80"),
    );

    fs::write(service_dir.join("Cargo.toml"), cargo_content)?;
    files.push(format!("services/{}/Cargo.toml", service.name));

    let lib_content = format!(
        r#"//! {}

pub fn version() -> &'static str {{
    env!("CARGO_PKG_VERSION")
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[test]
    fn test_version() {{
        assert!(!version().is_empty());
    }}
}}
"#,
        service.description
    );

    let src_dir = service_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    fs::write(src_dir.join("lib.rs"), lib_content)?;
    files.push(format!("services/{}/src/lib.rs", service.name));

    Ok(())
}

fn generate_tool(
    output_dir: &Path,
    tool: &crate::types::ToolConfig,
    plan: &Plan,
    tera: &mut Tera,
    context: &mut Context,
    files: &mut Vec<String>,
) -> Result<()> {
    let tool_dir = output_dir.join("tools").join(&tool.name);
    fs::create_dir_all(&tool_dir)?;

    let cargo_content = format!(
        r#"[package]
name = "{}"
version = "{}"
edition = "2021"
rust-version = "{}"

[[bin]]
name = "{}"
path = "src/main.rs"

[dependencies]
clap = {{ version = "4.5", features = ["derive"] }}
tokio = {{ workspace = true }}
serde = {{ workspace = true }}
serde_json = {{ workspace = true }}
anyhow = {{ workspace = true }}
tracing = {{ workspace = true }}
tracing-subscriber = {{ workspace = true }}
"#,
        tool.name,
        plan.project.version,
        plan.project.rust_version.as_deref().unwrap_or("1.80"),
        tool.name,
    );

    fs::write(tool_dir.join("Cargo.toml"), cargo_content)?;
    files.push(format!("tools/{}/Cargo.toml", tool.name));

    let main_content = format!(
        r#"//! {}

use clap::Parser;
use anyhow::Result;

#[derive(Parser)]
#[command(name = "{}", about = "{}", version)]
struct Cli {{
    #[arg(short, long, help = "Enable verbose output")]
    verbose: bool,
}}

#[tokio::main]
async fn main() -> Result<()> {{
    let cli = Cli::parse();

    if cli.verbose {{
        tracing_subscriber::fmt()
            .with_max_level(tracing::Level::DEBUG)
            .init();
    }} else {{
        tracing_subscriber::fmt()
            .with_max_level(tracing::Level::INFO)
            .init();
    }}

    tracing::info!("Running {}", env!("CARGO_PKG_NAME"));
    
    Ok(())
}}
"#,
        tool.description,
        tool.name,
        tool.description,
    );

    let src_dir = tool_dir.join("src");
    fs::create_dir_all(&src_dir)?;
    fs::write(src_dir.join("main.rs"), main_content)?;
    files.push(format!("tools/{}/src/main.rs", tool.name));

    Ok(())
}

fn write_github_workflows(
    output_dir: &Path,
    plan: &Plan,
    tera: &mut Tera,
    context: &mut Context,
    files: &mut Vec<String>,
) -> Result<()> {
    let workflow_dir = output_dir.join(".github/workflows");
    fs::create_dir_all(&workflow_dir)?;

    let ci_content = format!(
        r#"name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{{{ env.RUST_VERSION }}}}
        targets: x86_64-unknown-linux-musl,wasm32-unknown-unknown
        components: rustfmt,clippy
    
    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{{{ runner.os }}}}-cargo-${{{{ hashFiles('**/Cargo.lock') }}}}
    
    - name: Check formatting
      run: cargo fmt --all -- --check
    
    - name: Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
    
    - name: Test
      run: cargo test --workspace --all-features
    
    - name: Build x86_64-musl
      run: cargo build --release --target x86_64-unknown-linux-musl
    
    - name: Build wasm32
      run: cargo build --release --target wasm32-unknown-unknown

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Syft
      uses: anchore/sbom-action/download-syft@v0
    
    - name: Generate SBOM
      run: syft dir:. -o spdx-json > sbom.spdx.json
    
    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: sbom.spdx.json

  sign:
    name: Sign artifacts
    runs-on: ubuntu-latest
    needs: [test, sbom]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{{{ env.RUST_VERSION }}}}
        targets: x86_64-unknown-linux-musl
    
    - name: Build release
      run: cargo build --release --target x86_64-unknown-linux-musl
    
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3
    
    - name: Sign binary
      run: |
        cosign sign-blob \
          --yes \
          --output-signature target/x86_64-unknown-linux-musl/release/{}.sig \
          --output-certificate target/x86_64-unknown-linux-musl/release/{}.crt \
          target/x86_64-unknown-linux-musl/release/{}
"#,
        plan.project.rust_version.as_deref().unwrap_or("stable"),
        plan.project.name,
        plan.project.name,
        plan.project.name,
    );

    fs::write(workflow_dir.join("ci.yml"), ci_content)?;
    files.push(".github/workflows/ci.yml".to_string());

    Ok(())
}

fn load_templates(tera: &mut Tera) -> Result<()> {
    Ok(())
}